name: Tests

on: [push, pull_request]

jobs:
  tests:

    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json', 'composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, ctype, dom, fileinfo, intl, gd, json, mbstring, pdo, pdo_sqlite, openssl, sqlite, xml, zip
          coverage: none

      - name: Install composer
        run: composer install --no-interaction --no-scripts --no-suggest

      - name: Execute tests
        run: vendor/bin/pest

      - name: Debug cache
        run: |
          ls -la ~/.composer/cache/files
          composer config -g cache-dir
